//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Company.Workshop8.Workshop8Diagram")]

namespace Company.Workshop8
{
	/// <summary>
	/// DomainClass Workshop8Diagram
	/// Description for Company.Workshop8.Workshop8Diagram
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Workshop8.Workshop8Diagram.DisplayName", typeof(global::Company.Workshop8.Workshop8DomainModel), "Company.Workshop8.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Workshop8.Workshop8Diagram.Description", typeof(global::Company.Workshop8.Workshop8DomainModel), "Company.Workshop8.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Workshop8.Workshop8DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("57713fb9-5261-4f4e-bb0e-4c3c92f3308a")]
	public partial class Workshop8Diagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::Company.Workshop8.Workshop8ToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		
		/// <summary>
		/// Most connectors are mapped to element links, but there can be exceptions. This method tell if a connector should be
		/// mapped to an element link.
		/// </summary>
		public override bool IsConnectorMappedToLink(DslDiagrams::BinaryLinkShape connector)
		{
			#region Check Parameters
			global::System.Diagnostics.Debug.Assert(connector != null);
			if (connector == null)
				throw new global::System.ArgumentNullException("connector");
			#endregion
			if (connector.GetType() == typeof(global::Company.Workshop8.ExampleConnector))
				return false;
			if (connector.GetType() == typeof(global::Company.Workshop8.Relationship))
				return false;
			return base.IsConnectorMappedToLink(connector);
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::Company.Workshop8.Structural)
			{
				global::Company.Workshop8.StructuralShape newShape = new global::Company.Workshop8.StructuralShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Workshop8.Enabling)
			{
				global::Company.Workshop8.EnablingShape newShape = new global::Company.Workshop8.EnablingShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Workshop8.Immediate)
			{
				global::Company.Workshop8.ImmediateShape newShape = new global::Company.Workshop8.ImmediateShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Workshop8.EconomicConcern)
			{
				global::Company.Workshop8.EconomicConcernShape newShape = new global::Company.Workshop8.EconomicConcernShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Workshop8.SocialConcern)
			{
				global::Company.Workshop8.SocialConcernShape newShape = new global::Company.Workshop8.SocialConcernShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Workshop8.EnvironmentalConcern)
			{
				global::Company.Workshop8.EnvironmentalConcernShape newShape = new global::Company.Workshop8.EnvironmentalConcernShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Workshop8.TechnicalConcern)
			{
				global::Company.Workshop8.TechnicalConcernShape newShape = new global::Company.Workshop8.TechnicalConcernShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Workshop8.ImpactLevel)
			{
				global::Company.Workshop8.ExampleShape newShape = new global::Company.Workshop8.ExampleShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::Company.Workshop8.ExampleShape.DecoratorsInitialized += ExampleShapeDecoratorMap.OnDecoratorsInitialized;
			global::Company.Workshop8.EconomicConcernShape.DecoratorsInitialized += EconomicConcernShapeDecoratorMap.OnDecoratorsInitialized;
			global::Company.Workshop8.SocialConcernShape.DecoratorsInitialized += SocialConcernShapeDecoratorMap.OnDecoratorsInitialized;
			global::Company.Workshop8.EnvironmentalConcernShape.DecoratorsInitialized += EnvironmentalConcernShapeDecoratorMap.OnDecoratorsInitialized;
			global::Company.Workshop8.TechnicalConcernShape.DecoratorsInitialized += TechnicalConcernShapeDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ExampleShape.
		/// </summary>
		internal static partial class ExampleShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ExampleShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.Workshop8.ImpactLevel.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EconomicConcernShape.
		/// </summary>
		internal static partial class EconomicConcernShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EconomicConcernShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.Workshop8.EconomicConcern.EcoNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "EcoShapeName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for SocialConcernShape.
		/// </summary>
		internal static partial class SocialConcernShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for SocialConcernShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.Workshop8.SocialConcern.SocialNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SocialShapeName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EnvironmentalConcernShape.
		/// </summary>
		internal static partial class EnvironmentalConcernShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EnvironmentalConcernShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.Workshop8.EnvironmentalConcern.EnvironmentalNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "EnvironmentalShapeName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for TechnicalConcernShape.
		/// </summary>
		internal static partial class TechnicalConcernShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for TechnicalConcernShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.Workshop8.TechnicalConcern.TechNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TechnicalShapeName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::Company.Workshop8.RelationshipConnectAction relationshipConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::Company.Workshop8.Workshop8ToolboxHelper.RelationshipFilterString))
				{
					if (this.relationshipConnectAction == null)
					{
						this.relationshipConnectAction = new global::Company.Workshop8.RelationshipConnectAction(this);
						this.relationshipConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relationshipConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.relationshipConnectAction != null)
					{
						this.relationshipConnectAction.Dispose();
						this.relationshipConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// Workshop8Diagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x57713fb9, 0x5261, 0x4f4e, 0xbb, 0x0e, 0x4c, 0x3c, 0x92, 0xf3, 0x30, 0x8a);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Workshop8Diagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Workshop8Diagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Company.Workshop8
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Company.Workshop8.Structural), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Workshop8.Enabling), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Workshop8.Immediate), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Workshop8.EconomicConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Workshop8.SocialConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Workshop8.EnvironmentalConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Workshop8.TechnicalConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Workshop8.ImpactLevel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is global::Company.Workshop8.Structural)
				{
					parentElement = GetParentForStructural((global::Company.Workshop8.Structural)childElement);
				} else
				if(childElement is global::Company.Workshop8.Enabling)
				{
					parentElement = GetParentForEnabling((global::Company.Workshop8.Enabling)childElement);
				} else
				if(childElement is global::Company.Workshop8.Immediate)
				{
					parentElement = GetParentForImmediate((global::Company.Workshop8.Immediate)childElement);
				} else
				if(childElement is global::Company.Workshop8.EconomicConcern)
				{
					parentElement = GetParentForEconomicConcern((global::Company.Workshop8.EconomicConcern)childElement);
				} else
				if(childElement is global::Company.Workshop8.SocialConcern)
				{
					parentElement = GetParentForSocialConcern((global::Company.Workshop8.SocialConcern)childElement);
				} else
				if(childElement is global::Company.Workshop8.EnvironmentalConcern)
				{
					parentElement = GetParentForEnvironmentalConcern((global::Company.Workshop8.EnvironmentalConcern)childElement);
				} else
				if(childElement is global::Company.Workshop8.TechnicalConcern)
				{
					parentElement = GetParentForTechnicalConcern((global::Company.Workshop8.TechnicalConcern)childElement);
				} else
				if(childElement is global::Company.Workshop8.ImpactLevel)
				{
					parentElement = GetParentForImpactLevel((global::Company.Workshop8.ImpactLevel)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::Company.Workshop8.SoftwareArchitecture GetParentForImpactLevel( global::Company.Workshop8.ImpactLevel root )
			{
				// Segments 0 and 1
				global::Company.Workshop8.SoftwareArchitecture result = root.SoftwareArchitecture;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Workshop8.SoftwareArchitecture GetParentForStructural( global::Company.Workshop8.ImpactLevel root )
			{
				// Segments 0 and 1
				global::Company.Workshop8.SoftwareArchitecture result = root.SoftwareArchitecture;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Workshop8.SoftwareArchitecture GetParentForEnabling( global::Company.Workshop8.ImpactLevel root )
			{
				// Segments 0 and 1
				global::Company.Workshop8.SoftwareArchitecture result = root.SoftwareArchitecture;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Workshop8.SoftwareArchitecture GetParentForImmediate( global::Company.Workshop8.ImpactLevel root )
			{
				// Segments 0 and 1
				global::Company.Workshop8.SoftwareArchitecture result = root.SoftwareArchitecture;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Workshop8.SoftwareArchitecture GetParentForEconomicConcern( global::Company.Workshop8.Concern root )
			{
				// Segments 0 and 1
				global::Company.Workshop8.ImpactLevel root2 = root.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.Workshop8.SoftwareArchitecture result = root2.SoftwareArchitecture;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Workshop8.SoftwareArchitecture GetParentForSocialConcern( global::Company.Workshop8.Concern root )
			{
				// Segments 0 and 1
				global::Company.Workshop8.ImpactLevel root2 = root.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.Workshop8.SoftwareArchitecture result = root2.SoftwareArchitecture;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Workshop8.SoftwareArchitecture GetParentForEnvironmentalConcern( global::Company.Workshop8.Concern root )
			{
				// Segments 0 and 1
				global::Company.Workshop8.ImpactLevel root2 = root.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.Workshop8.SoftwareArchitecture result = root2.SoftwareArchitecture;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Workshop8.SoftwareArchitecture GetParentForTechnicalConcern( global::Company.Workshop8.Concern root )
			{
				// Segments 0 and 1
				global::Company.Workshop8.ImpactLevel root2 = root.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.Workshop8.SoftwareArchitecture result = root2.SoftwareArchitecture;
				if ( result == null ) return null;
				return result;
			}
		}
		
	
	}
