//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Workshop8
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "Workshop8";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Workshop8";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID Workshop8DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Workshop8CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID Workshop8ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Workshop8CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewWorkshop8ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Workshop8CommandSetId), 0x0001);
	
		// Package identifier
		public const string Workshop8PackageId = "42dbfdfa-208e-4bb3-a44d-4b3fefca676c";
		
		// Editor factory identifier
		public const string Workshop8EditorFactoryId = "1464560f-7582-4d77-9645-ff90379f139d";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string Workshop8ModelExplorerToolWindowId = "bed76667-0591-4d82-9d1a-271fdcf344ef";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.Workshop8
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string Workshop8CommandSetId = "f06a9544-579b-4b39-9f1d-cdd6bde45347";
	}
}